# Generated by Django 4.2.1 on 2023-05-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookvenue",
            name="club_name",
            field=models.CharField(default="club", max_length=255),
        ),
        migrations.AddField(
            model_name="bookvenue",
            name="event_desp",
            field=models.TextField(default="event description"),
        ),
        migrations.AddField(
            model_name="bookvenue",
            name="event_name",
            field=models.CharField(default="event name xyz", max_length=255),
        ),
    ]
