# Generated by Django 4.2.1 on 2023-05-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_bookvenue_club_name_bookvenue_event_desp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookvenue",
            name="aud_count",
            field=models.IntegerField(default=0),
        ),
    ]
