# Generated by Django 4.2.1 on 2023-05-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_bookvenue_aud_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookvenue",
            name="venue",
            field=models.CharField(default="venue name xyz", max_length=255),
        ),
    ]
