# Generated by Django 4.2.1 on 2023-05-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_bookvenue_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookvenue",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
