# Generated by Django 4.2.1 on 2023-05-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_alter_bookvenue_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookvenue",
            name="status",
            field=models.BooleanField(null=True),
        ),
    ]
