# Generated by Django 4.2.1 on 2023-05-31 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_alter_bookvenue_venue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookvenue",
            old_name="event_date",
            new_name="end_date",
        ),
        migrations.AddField(
            model_name="bookvenue",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
