# Generated by Django 4.2.1 on 2023-06-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_rename_event_date_bookvenue_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookvenue",
            name="contact_number",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
